import React, { createContext, useContext, useState, useEffect } from 'react';

// 1. TRANSLATION STRINGS
const translations = {
    en: {
        home: "Home",
        notes: "Notes",
        settings: "Settings",
        about: "About",
        trash: "Trash",
        empty: "Empty",
        welcome: "Welcome to Your Second Brain",
        pinned: "Pinned",
        pin: "Pin",
        other: "Others",
        recent: "Recent",
        searchPlaceholder: "Search notes...",
        resetSettings: "Reset Settings",
        resetConfirm: "Reset all settings to default?",
        resetButton: "Reset All",
        edit: "Edit",
        delete: "Delete",
        summarize: "Summarize",
        suggestTitle: "Suggest Title",
        tags: "Tags",
        unpin: "Unpin",
        export: "Export",
        restore: "Restore",
        deletePermanently: "Delete Permanently",
        created: "Created",
        lastEdited: "Last edited",
        theme: "Theme",
        fontSize: "Font Size",
        sort: "Sort Notes By",
        sortPreference: "Sort Preference",
        exportFormat: "Export Format",
        filter: "Filtering by tag ",
        clearFilter: "Clear Filter",
        language: "Language",
        darkMode: "Dark Mode",
        lightMode: "Light Mode",
        small: "Small",
        large: "Large",
        medium: "Medium",
        newestFirst: "Newest First",
        oldestFirst: "Oldest First",
        alphabetical: "A–Z_Title",
        default: "Default",
        is: "is",
        no: "No",
        yet: "yet",
        openNote: "Open Notes",
        quickAction: "Quick Actions",
        viewNote: "View Notes",
        newNote: "New Note",
        yourNote: "Your Notes",
      },
      es: {
        home: "Inicio",
        notes: "Notas",
        settings: "Configuración",
        about: "Acerca de",
        trash: "Papelera",
        empty: "Vacia",
        welcome: "Bienvenido a tu Second Brain",
        pinned: "Fijadas",
        pin: "Fijar",
        other: "Otras",
        recent: "Recientes",
        searchPlaceholder: "Buscar notas...",
        resetSettings: "Restablecer Configuraciones",
        resetConfirm: "¿Restablecer todas las configuraciones?",
        resetButton: "Restablecer todo",
        edit: "Editar",
        delete: "Eliminar",
        summarize: "Resumir",
        suggestTitle: "Sugerir Título",
        tags: "Etiquetas",
        unpin: "Desfijar",
        export: "exportación",
        restore: "Restaurar",
        deletePermanently: "Eliminar permanentemente",
        created: "Creado",
        lastEdited: "Ultima edición",
        theme: "Tema",
        fontSize: "Tamaño de fuente",
        sort: "Ordenar notas por",
        sortPreference: "Preferencia de ordenamiento",
        exportFormat: "Formato de exportación",
        filter: "Filtrar por etiqueta",
        clearFilter: "Limpiar filtro",
        language: "Idioma",
        darkMode: "Modo oscuro",
        lightMode: "Modo claro",
        small: "Pequeño",
        large: "Grande",
        medium: "Mediano",
        newestFirst: "Recientes primero",
        oldestFirst: "Antiguas primero",
        alphabetical: "A–Z_Titulo",
        default: "Predeterminado",
        is: "es",
        no: "No",
        yet: "aun",
        openNote: "Abrir Notas",
        quickAction: "Acciones rapidas",
        viewNote: "Ver Notas",
        newNote: "Nueva Nota",
        yourNote: "Tus Notas",
      },
      fr: {
        home: "Accueil",
        notes: "Notes",
        settings: "Paramètres",
        about: "A propos",
        trash: "Corbeille",
        empty: "Vide",
        welcome: "Bienvenue sur votre Second Brain",
        pinned: "Épinglées",
        pin: "Épingler",
        other: "Autres",
        recent: "Récentes",
        searchPlaceholder: "Rechercher des notes...",
        resetSettings: "Réinitialiser Paramètres ",
        resetConfirm: "Réinitialiser tous les paramètres par défaut ?",
        resetButton: "Tout réinitialiser",
        edit: "Modifier",
        delete: "Supprimer",
        summarize: "Résumer",
        suggestTitle: "Suggestion de titre",
        tags: "Tags",
        unpin: "Dépingler",
        export: "exportation",
        restore: "Restaurer",
        deletePermanently: "Supprimer permanentement",
        created: "Créé",
        lastEdited: "Dernière modification",
        theme: "Thème",
        fontSize: "Taille de police",
        sort: "Trier les notes par",
        sortPreference: "Préférence de tri",
        exportFormat: "Format d'exportation",
        filter: "Filtrer par tag",
        clearFilter: "Effacer le filtre",
        language: "Langue",
        darkMode: "Mode sombre",
        lightMode: "Mode clair",
        small: "Petit",
        large: "Grand",
        medium: "Moyen",
        newestFirst: "Les plus nouvelles premieres",
        oldestFirst: "Les plus anciennes premieres",
        alphabetical: "A–Z_Titre",
        default: "Par défaut",
        is: "est",
        no: "Non",
        yet: "encore",
        openNote: "Ouvrir les notes",
        quickAction: "Actions rapides",
        viewNote: "Voir les notes",
        newNote: "Nouvelle note",
        yourNote: "Vos notes",

      },
      de: {
        home: "Startseite",
        notes: "Notizen",
        settings: "Einstellungen",
        about: "About",
        trash: "Papierkorb",
        empty: "Leer",
        welcome: "Willkommen bei deinem Second Brain",
        pinned: "Angeheftet",
        pin: "Anheften",
        other: "Andere",
        recent: "Neueste",
        searchPlaceholder: "Notizen suchen...",
        resetSettings: "Einstellungen Zurücksetzen",
        resetConfirm: "Alle Einstellungen zurücksetzen?",
        resetButton: "Alles zurücksetzen",
        edit: "Bearbeiten",
        delete: "Löschen",
        summarize: "Zusammenfassen",
        suggestTitle: "Titel vorschlagen",
        tags: "Tags",
        unpin: "Anheften",
        export: "Exportieren",
        restore: "Wiederherstellen",
        deletePermanently: "Dauerhaft löschen",
        created: "Erstellt",
        lastEdited: "Zuletzt bearbeitet",
        theme: "Thema",
        fontSize: "Schriftgröße",
        sort: "Notizen sortieren nach",
        sortPreference: "Sortierungspräferenz",
        exportFormat: "Export-Format",
        filter: "Nach Tag filtern",
        clearFilter: "Filter löschen",
        language: "Sprache",
        darkMode: "Dunkler Modus",
        lightMode: "Heller Modus",
        small: "Kleine",
        large: "Große",
        medium: "Mittlere",
        newestFirst: "Neueste zuerst",
        oldestFirst: "Aeltere zuerst",
        alphabetical: "A–Z_Titel",
        default: "Standard",
        is: "ist",
        no: "Nein",
        yet: "noch",
        openNote: "Notizen ôffnen",
        quickAction: "Schnelle Aktionen",
        viewNote: "Notizen anzeigen",
        newNote: "Neue Notiz",
        yourNote: "Deine Notizen",
      },
};

// 2. SETTINGS CONTEXT
const SettingsContext = createContext();

export const SettingsProvider = ({ children }) => {
  const [fontSize, setFontSize] = useState(() => localStorage.getItem('fontSize') || 'medium');
  const [exportFormat, setExportFormat] = useState(() => localStorage.getItem('exportFormat') || 'txt');
  const [sortPreference, setSortPreference] = useState(() => localStorage.getItem('sortPreference') || 'newest');
  const [language, setLanguage] = useState(() => localStorage.getItem('language') || 'en');

  useEffect(() => {
    localStorage.setItem('fontSize', fontSize);
    localStorage.setItem('exportFormat', exportFormat);
    localStorage.setItem('sortPreference', sortPreference);
    localStorage.setItem('language', language);
  }, [fontSize, exportFormat, sortPreference, language]);

  const resetSettings = () => {
    setFontSize('medium');
    setExportFormat('txt');
    setSortPreference('newest');
    setLanguage('en');
  };

  const t = (key) => translations[language]?.[key] || key;

  return (
    <SettingsContext.Provider
      value={{
        fontSize,
        setFontSize,
        exportFormat,
        setExportFormat,
        sortPreference,
        setSortPreference,
        language,
        setLanguage,
        resetSettings,
        t,
      }}
    >
      {children}
    </SettingsContext.Provider>
  );
};

export const useSettings = () => useContext(SettingsContext);


